name = "MultivariateAnomalies"
uuid = "6b1494d1-c0e4-5e11-970b-cb64accc6d0e"
authors = ["milanflach <milanflach fs@users.noreply.github.com>"]
version = "0.2.4"
license = "MIT"
keywords = ["novelty detection", "anomaly detection", "outlier detection", "statistical process control", "process monitoring"]
repository = "https://github.com/milanflach/MultivariateAnomalies.jl.git"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
LIBSVM = "b1bec4e5-fd48-53fe-b0cb-9723c09d164b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
#MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

# [compat]
# MultivariateStats = ">=0.6.0"
